export class Report {
    REPORTID!: number;
    reportName!: string;
    histortOfMaxDays!: number;
    nonSpoolFile!: number;
    description!: string;
    title!: string;
    Abstract!: string;
    expirationDays!: number;
    skipPages!: number;
    uploadedFileName!: string;
    creationDate!: number;
    allowPrnt!: number;
    addedBy!: string;
    modifiedBy!: string;
    as400Id!: number;
    status!: string;
    deletedBy!: string;
    multiReports!: string;
    fileName!: string;
    allowOverrides!: number;
    numColumns!: number;
    confidential!: number;
    bireport!: string;
    helpUrl!: string;
    help!: string;
    detailDescription!: string;
    combinePdfReport!: number;
}
